### ISSUE TITLE
Multithreading support of ZSL

### ISSUE THREAD

**Issue by ghost** [AtteqCom/zsl#33]
How will ZSL handle multiple threads?
How will it handle high load?
How the celery support will deal with multiple threads?

**Comment by babky-atteq** [comment]
Check #32 for example and https://github.com/AtteqCom/zsl/pull/22/files/54fa45f447d4aa45fb4a0d801edf791640a96d35 comment "How ZSL will handle that" by Peter.

**Comment by babky** [comment]
It should be now fine.
