### ISSUE TITLE
Use correct logging methods in error_handler 

### ISSUE THREAD

**Issue by morihladko** [AtteqCom/zsl#36]
In `zsl.interface.webservice.utils.error_handler` use the appropriate logging methods in

```python
        try:
            return f(*args, **kwargs)
        except ImportError as ie:
            logging.error(str(ie) + "\n" + traceback.format_exc())
            return str(ie), 404
```
use logging.exception which may fit better to this case and should be outputted only in debug mode. Otherwise we should output something less informative.

**Comment by babky** [comment]
this was completely refactored
