### ISSUE TITLE
Add zsl.tasks.zsl.cors_test_task to documentation

### ISSUE THREAD

**Issue by morihladko** [AtteqCom/zsl#71]
Currently the module fails to import during making the documentation, because it depends on `@crossdomain` decorator, which expect an already initialized application to be present.

After fixing add it to api.rst.

**Comment by babky-atteq** [comment]
My bad, should I fix it?

**Comment by morihladko** [comment]
It's up to you, but the main issue is with the `@crossdomain` decorator, which depends on application state during import, all code which is state depended should be written as callbacks or factories.

**Comment by babky-atteq** [comment]
ignore this issue, if not blocking, i'll do that since i wanted to make a cors refactoring...

**Comment by babky-atteq** [comment]
does this really happen?

**Comment by babky** [comment]
this is now outdated
